package nandansatheesh.github.io.startupnamegenerator.constants;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public interface Constants {

    List<String> PREFIXES = Arrays.asList(
            "active",
            "arc",
            "auto",
            "app",
            "avi",
            "base",
            "co",
            "con",
            "core",
            "clear",
            "en",
            "echo",
            "even",
            "ever",
            "fair",
            "go",
            "high",
            "hyper",
            "in",
            "inter",
            "iso",
            "jump",
            "live",
            "make",
            "mass",
            "meta",
            "matter",
            "omni",
            "on",
            "one",
            "open",
            "over",
            "out",
            "re",
            "real",
            "peak",
            "pure",
            "shift",
            "silver",
            "solid",
            "spark",
            "start",
            "true",
            "up",
            "vibe"
    );

    List<String> WORD_SUFFIXES = Arrays.asList(
            "arc",
            "atlas",
            "base",
            "bay",
            "boost",
            "capsule",
            "case",
            "center",
            "cast",
            "click",
            "dash",
            "deck",
            "dock",
            "dot",
            "drop",
            "engine",
            "flow",
            "glow",
            "grid",
            "gram",
            "graph",
            "hub",
            "focus",
            "kit",
            "lab",
            "level",
            "layer",
            "light",
            "line",
            "logic",
            "load",
            "loop",
            "ment",
            "method",
            "mode",
            "mark",
            "ness",
            "now",
            "pass",
            "port",
            "post",
            "press",
            "prime",
            "push",
            "rise",
            "scape",
            "scale",
            "scan",
            "scout",
            "sense",
            "set",
            "shift",
            "ship",
            "side",
            "signal",
            "snap",
            "scope",
            "space",
            "span",
            "spark",
            "spot",
            "start",
            "storm",
            "stripe",
            "sync",
            "tap",
            "tilt",
            "ture",
            "type",
            "view",
            "verge",
            "vibe",
            "ware",
            "yard",
            "up"
    );

    List<String> ACTUAL_SUFFIX = Arrays.asList(
            "ary",
            "able",
            "ance",
            "ible",
            "ice",
            "ite",
            "er",
            "eon",
            "ent",
            "ful",
            "gent",
            "tion",
            "sion"
    );

    List<String> SUFFIXES = Stream.concat(WORD_SUFFIXES.stream(), ACTUAL_SUFFIX.stream())
            .collect(Collectors.toList());

}

